version: "3"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: test-BBDD
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "23506:3306"
  web:
    image: php:7.2.2-apache
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - "8000:80"
    stdin_open: true
    tty: true
